logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
server:
  port: 8189
  servlet:
    context-path: /
spring:
  flyway:
    enabled: true
    cleanOnValidationError: false
    cleanDisabled: false
    locations: classpath:db/migration
    schemas: master_schema
    baselineOnMigrate: true
    baselineVersion: 1
    validateOnMigrate: true
    outOfOrder: false
  datasource:
    url: jdbc:postgresql://172.20.0.9:5432/hackaton
#    url: jdbc:postgresql://localhost:5432/hackaton
    username: admin
    password: E2#QWDr321c%jiGHDShewfdwe
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      default-schema: master_schema